vich_uploader:
    db_driver: orm

    mappings:
        my_picture:
            uri_prefix: /images/
            upload_destination: '%kernel.project_dir%/public/images/test'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
